language: php
php:
  - 5.6
install: composer install
script: 
  - vendor/bin/codecept run unit --coverage --coverage-xml
  - cp tests/_output/coverage.xml build/logs/clover.xml
after_script:
  - vendor/bin/test-reporter
